#!/usr/bin/env python3
"""
Stub governance validator — generated by eco scaffold_project.py.

This is a minimal placeholder. Replace with the full eco validate_governance.py
(from https://github.com/jj-ervin/.eco) once you are ready for full enforcement.

In the meantime, governance_mode: stub means this exits 0 (clean) always,
while still listing any issues as warnings.
"""
import argparse
import json
import re
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--diagnostics-file', default=None)
    parser.add_argument('--update-hash', action='store_true')
    return parser.parse_args()


def read_project_mode(eco_dir):
    path = eco_dir / 'project.yaml'
    if not path.exists():
        return 'stub'
    text = path.read_text(encoding='utf-8')
    m = re.search(r'^\s*governance_mode:\s*[\"\']?(\w+)[\"\']?', text, re.MULTILINE)
    if m:
        return m.group(1).lower()
    return 'stub'


def run(args):
    eco_dir = Path(__file__).resolve().parents[1]
    mode = read_project_mode(eco_dir)
    diags = []

    required_files = [
        'enforcement.yaml', 'devpath.md', 'audit-log.md',
        'change-ledger.md', 'passchangelog.md', 'agent-log.md',
        'governance-hash.yaml',
    ]
    for f in required_files:
        if not (eco_dir / f).exists():
            diags.append({'severity': 'error', 'message': f'Missing required file: {f}', 'rule': 'STUB-GOVFILE'})

    # Warn about any [DECLARED] rules remaining
    enf = eco_dir / 'enforcement.yaml'
    if enf.exists():
        t = enf.read_text(encoding='utf-8')
        count = t.count('[DECLARED]')
        if count:
            diags.append({'severity': 'warning', 'message': f'{count} rules still [DECLARED] in enforcement.yaml', 'rule': 'STUB-DECLARED'})

    # In stub mode downgrade errors to warnings
    if mode == 'stub':
        for d in diags:
            if d['severity'] == 'error':
                d['severity'] = 'warning'

    if args.diagnostics_file:
        Path(args.diagnostics_file).write_text(json.dumps({'governance_mode': mode, 'issues': diags}, indent=2), encoding='utf-8')

    for d in diags:
        print(f"[{d['severity'].upper()}] {d['message']}")

    has_errors = any(d['severity'] == 'error' for d in diags)
    if not has_errors:
        suffix = ' (stub mode)' if mode == 'stub' else ''
        print(f'[OK] governance validation passed{suffix}')
    return 1 if has_errors else 0


def main():
    args = parse_args()
    sys.exit(run(args))


if __name__ == '__main__':
    main()
